""" X509Certificate is a class for managing X509 certificates

    Proxy RFC: https://tools.ietf.org/html/rfc38200
    X509RFC: https://tools.ietf.org/html/rfc5280

"""

__RCSID__ = "$Id$"

import datetime
import functools
import os
import random
import time

import M2Crypto


from DIRAC import S_OK, S_ERROR
from DIRAC.Core.Utilities import Time
from DIRAC.Core.Utilities import DErrno
from DIRAC.ConfigurationSystem.Client.Helpers import Registry
from DIRAC.Core.Security.m2crypto import asn1_utils


def executeOnlyIfCertLoaded(meth):
  """ This decorator is a utility function just to avoid having to test in
      every methods whether the certificate has been properly loaded.
  """

  # This utilities allow to preserve the original help
  # Of the method being decorated
  @functools.wraps(meth)
  def innerFunc(*args, **kwargs):
    """ Test whether the certificate has been loaded.been
        If not returns S_ERROR()
    """
    self = args[0]
    if not self._certLoaded:  # pylint: disable=protected-access
      return S_ERROR(DErrno.ENOCERT)
    return meth(*args, **kwargs)

  return innerFunc


class X509Certificate(object):
  """ The X509Certificate object represents ... a X509Certificate.
      It is a wrapper around a lower level implementation (M2Crypto in this case) of a certificate.
      It can be a host or user certificate.

      Also, a proxy certificate is a X509Certificate, however it is useless without all the chain of issuers.
      That's why one has the X509Chain.

    """

  def __init__(self, x509Obj=None, certString=None):
    """
      Constructor.
      You can give either nothing, or the x509Obj or the certString

      :param x509Obj: (optional) certificate instance
      :type x509Obj: M2Crypto.X509.X509
      :param certString: text representation of certificate
      :type certString: String

    """

    self._certLoaded = False
    if x509Obj:
      self.__certObj = x509Obj
      self._certLoaded = True
    # else:
    #   self.__certObj = M2Crypto.X509.X509()
    #   self._certLoaded = True
    if certString:
      self.loadFromString(certString)

  # def getCertObject(self):
  #   """ Return the wrapped certificate

  #       :returns: ~M2Crypto.X509.X509 object
  #   """
  #   return self.__certObj

  # Pylint is surprisingly picky here, so remove that warning
  # pylint: disable=protected-access
  @classmethod
  def generateProxyCertFromIssuer(cls, x509Issuer, x509ExtensionStack, proxyKey, lifetime=3600):
    """ This class method is meant to generate a new X509Certificate out of an existing one.
        Basically, it generates a proxy... However, you can't have a proxy certificate working on
        its own, you need all the chain of certificates. This method is meant to be called
        only by the X509Chain class.

        Inspired from https://github.com/eventbrite/m2crypto/blob/master/demo/x509/ca.py#L45

        :param x509Issuer: X509Certificate instance from which we generate the next one
        :param x509ExtensionStack: M2Crypto.X509.X509_Extension_Stack object to add to the new certificate.
                                   It contains all the X509 extensions needed for the proxy (e.g. DIRAC group).
                                   See ~X509Chain.__getProxyExtensionList
        :param proxyKey: a M2Crypto.EVP.PKey instance with the RSA key already assigned, used to sign the certificate.
        :param lifetime: duration of the proxy in second. Default 3600


        :returns: a new X509Certificate

    """
    proxyCert = cls()

    proxyCert.__certObj = M2Crypto.X509.X509()

    # According to the proxy RFC, the serial
    # number just need to be uniqu among the proxy generated by the issuer.
    # The random module of python will be good enough for that
    serial = int(random.random() * 10 ** 10)
    proxyCert.__certObj.set_serial_number(serial)

    # No easy way to deep-copy certificate subject, since they are swig object

    # We basically get a string like 'O=Dirac Computing, O=CERN, CN=MrUser'
    # So we split it, and then re-add each entry after the other.

    proxySubject = M2Crypto.X509.X509_Name()

    issuerSubjectObj = x509Issuer.__certObj.get_subject()
    issuerSubjectParts = issuerSubjectObj.as_text().split(', ')

    for isPart in issuerSubjectParts:
      nid, val = isPart.split('=', 1)
      proxySubject.add_entry_by_txt(field=nid, type=M2Crypto.ASN1.MBSTRING_ASC, entry=val, len=-1, loc=-1, set=0)

    # Finally we add a random Common Name  component. And we might as well use the serial.. :)
    proxySubject.add_entry_by_txt(field="CN", type=M2Crypto.ASN1.MBSTRING_ASC,
                                  entry=str(serial), len=-1, loc=-1, set=0)

    proxyCert.__certObj.set_subject(proxySubject)

    # We now add all the extensions we wish to add
    for extension in x509ExtensionStack:
      proxyCert.__certObj.add_ext(extension)

    proxyCert.__certObj.set_issuer(issuerSubjectObj)

    # According to the X509 RFC, we are safe if we just copy the version
    # number from the issuer certificate
    proxyCert.__certObj.set_version(x509Issuer.__certObj.get_version())

    proxyCert.__certObj.set_pubkey(proxyKey)

    # Set the start of the validity a bit in the past
    # to be sure to be able to use it right now
    proxyNotBefore = M2Crypto.ASN1.ASN1_UTCTIME()
    proxyNotBefore.set_time(int(time.time()) - 900)
    proxyCert.__certObj.set_not_before(proxyNotBefore)

    # Set the end date of the validity according to the lifetime
    proxyNotAfter = M2Crypto.ASN1.ASN1_UTCTIME()
    proxyNotAfter.set_time(int(time.time()) + lifetime)
    proxyCert.__certObj.set_not_after(proxyNotAfter)

    # Finally set it as loaded. Care that it is not yet signed !!
    proxyCert._certLoaded = True

    return S_OK(proxyCert)

  def load(self, certificate):
    """ Load an x509 certificate either from a file or from a string

        :param certificate: path to the file or PEM encoded string

        :returns: S_OK on success, otherwise S_ERROR
    """

    if os.path.exists(certificate):
      return self.loadFromFile(certificate)

    return self.loadFromString(certificate)

  def loadFromFile(self, certLocation):
    """
       Load a x509 cert from a pem file

       :param certLocation: path to the certificate file

      :returns: S_OK / S_ERROR.

    """
    try:
      with open(certLocation, 'r') as fd:
        pemData = fd.read()
        return self.loadFromString(pemData)
    except IOError:
      return S_ERROR(DErrno.EOF, "Can't open %s file" % certLocation)

  def loadFromString(self, pemData):
    """
      Load a x509 cert from a string containing the pem data

      :param pemData: pem encoded string

      :returns: S_OK / S_ERROR
    """
    try:
      self.__certObj = M2Crypto.X509.load_cert_string(str(pemData), M2Crypto.X509.FORMAT_PEM)
    except BaseException as e:
      return S_ERROR(DErrno.ECERTREAD, "Can't load pem data: %s" % e)

    self._certLoaded = True
    return S_OK()

  @executeOnlyIfCertLoaded
  def hasExpired(self):
    """
      Check if the loaded certificate is still valid

      :returns: S_OK( True/False )/S_ERROR
    """

    res = self.getNotAfterDate()
    if not res['OK']:
      return res

    notAfter = res['Value']
    now = datetime.datetime.utcnow()

    return S_OK(notAfter < now)

  @executeOnlyIfCertLoaded
  def getNotAfterDate(self):
    """
      Get not after date of a certificate

      :returns: S_OK( datetime )/S_ERROR
    """

    notAfter = self.__certObj.get_not_after().get_datetime()

    # M2Crypto does things correctly by setting a timezone info in the datetime
    # However, we do not in DIRAC, and so we can't compare the dates.
    # We have to remove the timezone info from M2Crypto
    notAfter = notAfter.replace(tzinfo=None)

    return S_OK(notAfter)

  # @executeOnlyIfCertLoaded
  # def setNotAfter(self, notAfter):
  #   """
  #     Set not after date of a certificate. This method is not meant to be used, but to generate a proxy.

  #     :param notAfter: M2Crypto.ASN1.ASN1_UTCTIME object.

  #     :returns: S_OK/S_ERROR
  #   """

  #   self.__certObj.set_not_after(notAfter)

  #   return S_OK()

  @executeOnlyIfCertLoaded
  def getNotBeforeDate(self):
    """
      Get not before date of a certificate

      :returns: S_OK( datetime )/S_ERROR

    """
    return S_OK(self.__certObj.get_not_before().get_datetime())

  # @executeOnlyIfCertLoaded
  # def setNotBefore(self, notbefore):
  #   """
  #     Set not before date of a certificate This method is not meant to be used, but to generate a proxy.

  #     :returns: S_OK/S_ERROR
  #   """
  #   self.__certObj.set_not_before(notbefore)
  #   return S_OK()

  @executeOnlyIfCertLoaded
  def getSubjectDN(self):
    """
      Get subject DN

      :returns: S_OK( string )/S_ERROR
    """
    return S_OK(str(self.__certObj.get_subject()))

  @executeOnlyIfCertLoaded
  def getIssuerDN(self):
    """
      Get issuer DN

      :returns: S_OK( string )/S_ERROR
    """
    return S_OK(str(self.__certObj.get_issuer()))

  @executeOnlyIfCertLoaded
  def getSubjectNameObject(self):
    """
      Get subject name object

      :returns: S_OK( X509Name )/S_ERROR
    """
    return S_OK(self.__certObj.get_subject())

  @executeOnlyIfCertLoaded
  def getIssuerNameObject(self):
    """
      Get issuer name object

      :returns: S_OK( X509Name )/S_ERROR
    """
    return S_OK(self.__certObj.get_issuer())

  # @executeOnlyIfCertLoaded
  # def setIssuer(self, nameObject):
  #   """
  #     Set issuer name object

  #     :returns: S_OK/S_ERROR
  #   """
  #   self.__certObj.set_issuer(nameObject)
  #   return S_OK()

  @executeOnlyIfCertLoaded
  def getPublicKey(self):
    """
      Get the public key of the certificate
    """
    return S_OK(self.__certObj.get_pubkey())

  # @executeOnlyIfCertLoaded
  # def setPublicKey(self, pubkey):
  #   """
  #    Set the public key of the certificate
  #   """
  #   self.__certObj.set_pubkey(pubkey)
  #   return S_OK()

  # @executeOnlyIfCertLoaded
  # def getVersion(self):
  #   """
  #     Get the version of the certificate
  #   """
  #   return S_OK(self.__certObj.get_version())

  # @executeOnlyIfCertLoaded
  # def setVersion(self, version):
  #   """
  #    Set the version of the certificate
  #   """
  #   self.__certObj.set_version(version)
  #   return S_OK()

  @executeOnlyIfCertLoaded
  def getSerialNumber(self):
    """
      Get certificate serial number

      :returns: S_OK( serial )/S_ERROR
    """
    return S_OK(self.__certObj.get_serial_number())

  # @executeOnlyIfCertLoaded
  # def setSerialNumber(self, serial):
  #   """
  #     Set certificate serial number

  #     :returns: S_OK/S_ERROR
  #   """
  #   self.__certObj.set_serial_number(serial)
  #   return S_OK()

  @executeOnlyIfCertLoaded
  def sign(self, key, algo):
    """
      Sign the cerificate using provided key and algorithm.
    """
    self.__certObj.sign(key, algo)
    return S_OK()

  @executeOnlyIfCertLoaded
  def getDIRACGroup(self, ignoreDefault=False):
    """
      Get the dirac group if present
    """
    try:
      return S_OK(asn1_utils.decodeDIRACGroup(self.__certObj))
    except LookupError:
      pass

    # extCount = self.__certObj.get_ext_count()
    # for extIdx in xrange(extCount):
    #
    #   ext = self.__certObj.get_ext_at(extIdx)
    #   if ext.get_name() == "diracGroup":
    #     return S_OK(ext.get_value())
    if ignoreDefault:
      return S_OK(False)
    result = self.getIssuerDN()
    if not result['OK']:
      return result
    return Registry.findDefaultGroupForDN(result['Value'])

  @executeOnlyIfCertLoaded
  def hasVOMSExtensions(self):
    """
      Has voms extensions
    """
    try:
      self.__certObj.get_ext('vomsExtensions')
      return S_OK(True)
    except LookupError:
      # no extension found
      pass
    return S_OK(False)

  def getVOMSData(self):
    """
      Get voms extensions
    """
    try:
      vomsExt = asn1_utils.decodeVOMSExtension(self.__certObj)
      return S_OK(vomsExt)
    except LookupError:
      return S_ERROR(DErrno.EVOMS, "No VOMS data available")
    #
    # decoder = asn1.Decoder()
    # decoder.start(self.__certObj.as_der())
    # data = parseForVOMS(decoder)
    # if data:
    #   return S_OK(data)
    # else:
    #   return S_ERROR(DErrno.EVOMS, "No VOMS data available")

  @executeOnlyIfCertLoaded
  def generateProxyRequest(self, bitStrength=1024, limited=False):
    """
      Generate a proxy request
      Return S_OK( X509Request ) / S_ERROR
    """

    if not limited:
      subj = self.__certObj.get_subject()
      lastEntry = subj[len(subj) - 1]
      if lastEntry.get_data() == "limited proxy":
        limited = True

    from DIRAC.Core.Security.m2crypto.X509Request import X509Request

    req = X509Request()
    req.generateProxyRequest(bitStrength=bitStrength, limited=limited)
    return S_OK(req)

  @executeOnlyIfCertLoaded
  def getRemainingSecs(self):
    """
      Get remaining lifetime in secs
    """
    notAfter = self.__certObj.get_not_after().get_datetime()
    notAfter = notAfter.replace(tzinfo=Time.dateTime().tzinfo)
    remaining = notAfter - Time.dateTime()
    return S_OK(max(0, remaining.days * 86400 + remaining.seconds))

  @executeOnlyIfCertLoaded
  def getExtensions(self):
    """
      Get a decoded list of extensions
    """
    extList = []
    for i in xrange(self.__certObj.get_ext_count()):
      sn = self.__certObj.get_ext_at(i).get_name()
      try:
        value = self.__certObj.get_ext_at(i).get_value()
      except BaseException:
        value = "Cannot decode value"
      extList.append((sn, value))
    return S_OK(sorted(extList))

  @executeOnlyIfCertLoaded
  def verify(self, pkey):
    """
      Verify certificate using provided key

      :returns: S_OK(bool) where the boolean shows the success of the verification
    """
    ret = self.__certObj.verify(pkey)
    return S_OK(ret == 1)

  # @executeOnlyIfCertLoaded
  # def setSubject(self, subject):
  #   """
  #     Set subject using provided X509Name object
  #   """
  #   self.__certObj.set_subject(subject)
  #   return S_OK()

  # def get_subject(self):
  #   """
  #     Deprecated way of getting subject DN. Only for backward compatibility reasons.
  #   """
  #   # XXX This function should be deleted when all code depending on it is updated.
  #   return self.getSubjectDN()['Value']  # XXX FIXME awful awful hack

  @executeOnlyIfCertLoaded
  def asPem(self):
    """
      Return cerificate as PEM string
    """
    return self.__certObj.as_pem()

  @executeOnlyIfCertLoaded
  def getExtension(self, name):
    """
      Return X509 Extension with given name
    """
    try:
      ext = self.__certObj.get_ext(name)
    except LookupError as e:
      return S_ERROR(e)
    return S_OK(ext)

  # @executeOnlyIfCertLoaded
  # def addExtension(self, extension):
  #   """
  #     Add extension to the certificate
  #   """
  #   self.__certObj.add_ext(extension)
  #   return S_OK()
